<?php
define('_chinhsach','Chính sách');
define('_dangkynhantin','Đăng ký nhận tin');
define('_ketnoivoichungtoi','Kết nối với chúng tôi');
define('_placeholder_email','Nhập địa chỉ email');
define('_submit','Gửi Đăng ký');
define('_heading_nhan_tin','Gửi email của bạn để nhận ưu đãi độc quyền và hơn nữa');
define('_tintucnoibat','Tin tức nổi bật');
define('_xemthem','Xem thêm');
define('_thang','tháng');
define('_hinhanhthucte','Hình ảnh thực tế');
define('_dichvucuachungtoi','Dịch vụ của chúng tôi');
define('_gia','Giá');
define('_lienhe','Liên hệ');
define('_xemchitiet','Xem chi tiết');
define('_sanphammoi','Sản phẩm mới');
define('_noibat','Nổi bật');
define('_banchay','Bán chạy');
define('_trangchu','Trang chủ');
define('_gioithieu','Giới thiệu');
define('_sanpham','Sản phẩm');
define('_dichvu','Dịch vụ');
define('_chungnhan','Chứng nhận');
define('_tintuc','Tin tức');
define('_tuyendung','Tuyển dụng');
define('_diachi','Địa chỉ');
define('_mocua','Mở cửa');
define('_holdertextboxsearch','Tìm sản phẩm');
define('_tiengviet','Tiếng Việt');
define('_tienganh','English');
define('_dangcapnhat','Nội dung đang cập nhật');
define('_timkiem','Tìm kiếm');
define('_empty','Không tìm thấy sản phẩm nào theo từ khóa tìm kiếm');
define('_submit_contact','Gửi');
define('_ten','Tên');
define('_dienthoai','Điện thoại');
define('_tinnhan','Nội dung');
define('_chitiet','Chi tiết');
define('_sanphamkhac','Sản phẩm khác');
define('_baivietkhac','Bài viết khác');
define('_online','Đang online');
define('_ngay','Ngày');
define('_tong','Tổng truy cập');