<?php
define('_chinhsach','Policy');
define('_dangkynhantin','Sign up for');
define('_ketnoivoichungtoi','Connect with us');
define('_placeholder_email','Enter your email address');
define('_submit','Submit Registration');
define('_heading_nhan_tin','Send your email to receive exclusive deals and more');
define('_tintucnoibat','Featured news');
define('_xemthem','See more');
define('_thang','month');
define('_hinhanhthucte','Photo realistic');
define('_dichvucuachungtoi','Our services');
define('_gia','Price');
define('_lienhe','Contact');
define('_xemchitiet','See details');
define('_sanphammoi','New product');
define('_noibat','Featured product');
define('_banchay','Selling');
define('_trangchu','Home');
define('_gioithieu','Introduce');
define('_sanpham','Product');
define('_dichvu','Service');
define('_chungnhan','Certification');
define('_tintuc','News');
define('_tuyendung','Recruitment');
define('_diachi','Address');
define('_mocua','Open door');
define('_holdertextboxsearch','Find products');
define('_tiengviet','Vietnamese');
define('_tienganh','English');
define('_dangcapnhat','Coming soon');
define('_timkiem','Search');
define('_empty','No products were found by search term');
define('_submit_contact','Send');
define('_ten','Name');
define('_dienthoai','Phone');
define('_tinnhan','Content');
define('_chitiet','Detail');
define('_sanphamkhac','Other products');
define('_baivietkhac','Featured news');
define('_online','Online');
define('_ngay','Today');
define('_tong','Total');